using System;
using System.Collections.Generic;

#nullable disable

namespace SocialAPI.Models
{
    public partial class User
    {
        public uint UserId { get; set; }
        public byte UserGroup { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserEmailVerified { get; set; }
        public string UserEmailVerificationCode { get; set; }
        public string UserPhone { get; set; }
        public string UserPhoneVerified { get; set; }
        public string UserPhoneVerificationCode { get; set; }
        public string UserPassword { get; set; }
        public string UserTwoFactorEnabled { get; set; }
        public string UserTwoFactorType { get; set; }
        public string UserTwoFactorKey { get; set; }
        public string UserTwoFactorGsecret { get; set; }
        public string UserActivated { get; set; }
        public string UserReseted { get; set; }
        public string UserResetKey { get; set; }
        public string UserSubscribed { get; set; }
        public uint? UserPackage { get; set; }
        public DateTime? UserSubscriptionDate { get; set; }
        public uint UserBoostedPosts { get; set; }
        public uint UserBoostedPages { get; set; }
        public string UserStarted { get; set; }
        public string UserVerified { get; set; }
        public string UserBanned { get; set; }
        public uint UserLiveRequestsCounter { get; set; }
        public uint UserLiveRequestsLastid { get; set; }
        public uint UserLiveMessagesCounter { get; set; }
        public uint UserLiveMessagesLastid { get; set; }
        public uint UserLiveNotificationsCounter { get; set; }
        public uint UserLiveNotificationsLastid { get; set; }
        public string UserLatitude { get; set; }
        public string UserLongitude { get; set; }
        public DateTime? UserLocationUpdated { get; set; }
        public string UserFirstname { get; set; }
        public string UserLastname { get; set; }
        public string UserGender { get; set; }
        public string UserPicture { get; set; }
        public uint? UserPictureId { get; set; }
        public string UserCover { get; set; }
        public uint? UserCoverId { get; set; }
        public string UserCoverPosition { get; set; }
        public uint? UserAlbumPictures { get; set; }
        public uint? UserAlbumCovers { get; set; }
        public uint? UserAlbumTimeline { get; set; }
        public uint? UserPinnedPost { get; set; }
        public DateTime? UserRegistered { get; set; }
        public DateTime UserLastSeen { get; set; }
        public DateTime? UserFirstFailedLogin { get; set; }
        public string UserFailedLoginIp { get; set; }
        public uint UserFailedLoginCount { get; set; }
        public uint? UserCountry { get; set; }
        public DateTime? UserBirthdate { get; set; }
        public string UserRelationship { get; set; }
        public string UserBiography { get; set; }
        public string UserWebsite { get; set; }
        public string UserWorkTitle { get; set; }
        public string UserWorkPlace { get; set; }
        public string UserWorkUrl { get; set; }
        public string UserCurrentCity { get; set; }
        public string UserHometown { get; set; }
        public string UserEduMajor { get; set; }
        public string UserEduSchool { get; set; }
        public string UserEduClass { get; set; }
        public string UserSocialFacebook { get; set; }
        public string UserSocialTwitter { get; set; }
        public string UserSocialYoutube { get; set; }
        public string UserSocialInstagram { get; set; }
        public string UserSocialLinkedin { get; set; }
        public string UserSocialVkontakte { get; set; }
        public string UserProfileBackground { get; set; }
        public string UserChatEnabled { get; set; }
        public string UserPrivacyNewsletter { get; set; }
        public string UserPrivacyPoke { get; set; }
        public string UserPrivacyGifts { get; set; }
        public string UserPrivacyWall { get; set; }
        public string UserPrivacyBirthdate { get; set; }
        public string UserPrivacyRelationship { get; set; }
        public string UserPrivacyBasic { get; set; }
        public string UserPrivacyWork { get; set; }
        public string UserPrivacyLocation { get; set; }
        public string UserPrivacyEducation { get; set; }
        public string UserPrivacyOther { get; set; }
        public string UserPrivacyFriends { get; set; }
        public string UserPrivacyPhotos { get; set; }
        public string UserPrivacyPages { get; set; }
        public string UserPrivacyGroups { get; set; }
        public string UserPrivacyEvents { get; set; }
        public string EmailPostLikes { get; set; }
        public string EmailPostComments { get; set; }
        public string EmailPostShares { get; set; }
        public string EmailWallPosts { get; set; }
        public string EmailMentions { get; set; }
        public string EmailProfileVisits { get; set; }
        public string EmailFriendRequests { get; set; }
        public string FacebookConnected { get; set; }
        public string FacebookId { get; set; }
        public string GoogleConnected { get; set; }
        public string GoogleId { get; set; }
        public string TwitterConnected { get; set; }
        public string TwitterId { get; set; }
        public string InstagramConnected { get; set; }
        public string InstagramId { get; set; }
        public string LinkedinConnected { get; set; }
        public string LinkedinId { get; set; }
        public string VkontakteConnected { get; set; }
        public string VkontakteId { get; set; }
        public int? UserReferrerId { get; set; }
        public string UserAffiliateBalance { get; set; }
        public string UserWalletBalance { get; set; }
        public int UserPoints { get; set; }
        public string ChatSound { get; set; }
        public string NotificationsSound { get; set; }
        public string OnesignalUserId { get; set; }
        public string UserLanguage { get; set; }
    }
}
